### ISSUE TITLE
bug: Can't copy files from symbolic links

### ISSUE THREAD

**Issue by artemisart** [openvinotoolkit/cvat#1210] opened 2020-02-27 17:39 UTC
I tried creating a new task using symbolic links to images but the import fails with this message:
`Could not create the task on the server. distutils.errors.DistutilsFileError: can't copy '/home/django/share/pathpathpath/4379226.jpg': doesn't exist or not a regular file. Code: 400`

**Comment by alalek** [comment] 2020-02-27 19:36
> using symbolic links to images

Exact steps to reproduce?

Please note, `docker` technology doesn't handle symbolic links. It is user responsibility to make them readable in container (including mounting of extra volumes on right paths).

**Comment by artemisart** [comment] 2020-02-28 09:43
> Exact steps to reproduce?

Ex. in a folder with an image file `1.jpg` (I tried on the host machine where docker runs, but not inside the container), `mkdir images; ln -s images/link.jpg 1.jpg`, now create a new task with source: share, select the `images` folder, the upload fails.

> Please note, `docker` technology doesn't handle symbolic links. It is user responsibility to make them readable in container (including mounting of extra volumes on right paths).

I don't believe the error here is due to docker but not sure at all.

**Comment by nmanovic** [comment] 2020-02-29 03:39
@artemisart , @alalek , looks like should work in the scenario. Let's investigate.

**Comment by nmanovic** [comment] 2021-11-28 05:05
It looks like the scenario is artificial. I will close the issue as outdated.

**Closed by nmanovic** 2021-11-28 05:05 UTC
Labels: bug
