### ISSUE TITLE
Skeletal Point Annotation Support

### ISSUE THREAD

**Issue by anuradhag30** [openvinotoolkit/cvat#3983] opened 2021-12-02 17:58 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Design, label, and interpolate keypoint skeletons and custom polygons on image and video data. Required for Pose estimation

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment] 2021-12-07 09:07
Duplicate of #3254

**Closed by azhavoro** 2021-12-07 09:07 UTC

**Comment by csfankun** [comment] 2022-01-14 09:29
I really look forward for this skeleton annotation tool. and it will be excellent for download dataset as the coco-wholebody format
like this.
{
    "info": {
        "description": "COCO-WholeBody",
        "url": "https://github.com/jin-s13/COCO-WholeBody",
        "version": "1.0",
        "year": "2020",
        "date_created": "2020/07/01"
    },
    "licenses": [
        {
            "url": "http://creativecommons.org/licenses/by-nc-sa/2.0/",
            "id": 1,
            "name": "Attribution-NonCommercial-ShareAlike License"
        },
        {
            "url": "http://creativecommons.org/licenses/by-nc/2.0/",
            "id": 2,
            "name": "Attribution-NonCommercial License"
        }
    ],
    "images": [
        {
            "license": 2,
            "file_name": "000000569972.jpg",
            "coco_url": "http://images.cocodataset.org/val2017/000000569972.jpg",
            "height": 574,
            "width": 640,
            "date_captured": "2013-11-21 00:20:50",
            "flickr_url": "http://farm2.staticflickr.com/1429/5147095348_7c3f0734ec_z.jpg",
            "id": 569972
        }
    ],
    "annotations": [
        {
            "segmentation": [
                [
                    118.45,
                    365.77,
                    133.62,
                    363.7,
                    144.65,
                    340.26,
                    129.48,
                    296.81,
                    148.1,
                    275.43,
                    167.41,
                    309.22,
                    194.31,
                    329.91,
                    206.04,
                    327.15,
                    205.35,
                    322.32,
                    186.04,
                    311.98,
                    158.45,
                    259.56,
                    168.1,
                    258.18,
                    178.45,
                    244.39,
                    179.14,
                    238.87,
                    174.31,
                    229.91,
                    170.86,
                    225.08,
                    165.35,
                    225.08,
                    159.83,
                    227.84,
                    153.62,
                    233.35,
                    151.55,
                    239.56,
                    151.55,
                    242.32,
                    137.76,
                    242.32,
                    113.62,
                    255.42,
                    92.93,
                    295.43,
                    104.65,
                    318.19,
                    110.86,
                    323.7,
                    122.58,
                    335.43,
                    126.72,
                    343.01,
                    117.07,
                    363.02
                ]
            ],
            "num_keypoints": 16,
            "area": 5613.98945,
            "iscrowd": 0,
            "keypoints": [
                169,
                249,
                2,
                172,
                246,
                2,
                167,
                246,
                2,
                0,
                0,
                0,
                156,
                239,
                2,
                155,
                263,
                2,
                133,
                251,
                2,
                164,
                292,
                2,
                115,
                280,
                2,
                188,
                320,
                2,
                125,
                307,
                2,
                118,
                297,
                2,
                104,
                293,
                2,
                136,
                342,
                2,
                136,
                335,
                2,
                115,
                367,
                1,
                128,
                369,
                1
            ],
            "image_id": 569972,
            "bbox": [
                92.93,
                225.08,
                113.11,
                140.69
            ],
            "category_id": 1,
            "id": 186032,
            "face_box": [
                158.61,
                243.61,
                18.089999999999975,
                15.930000000000007
            ],
            "lefthand_box": [
                191.6,
                321.8,
                14.099999999999994,
                10.300000000000011
            ],
            "righthand_box": [
                124.1,
                309.4,
                12.099999999999994,
                19.100000000000023
            ],
            "lefthand_kpts": [
                192.9,
                322.4,
                1,
                196.15,
                322.8,
                1,
                199.4,
                323.2,
                1,
                202.2,
                324.1,
                1,
                204.3,
                325.6,
                1,
                200.7,
                330.3,
                1,
                203.4,
                329.9,
                2,
                204.2,
                327.1,
                2,
                204.2,
                324.8,
                2,
                200.1,
                330.9,
                2,
                202.5,
                328.6,
                2,
                202.8,
                326.4,
                2,
                202.3,
                324.2,
                2,
                199.2,
                331.0,
                2,
                200.8,
                328.6,
                2,
                201.4,
                326.5,
                2,
                200.7,
                324.2,
                2,
                197.2,
                330.2,
                2,
                199.4,
                328.9,
                2,
                199.8,
                327.1,
                2,
                199.2,
                325.2,
                2
            ],
            "righthand_kpts": [
                130.0,
                312.0,
                0.016195878386497498,
                132.0,
                318.0,
                0.010940216481685638,
                134.0,
                324.0,
                0.010940216481685638,
                134.0,
                324.0,
                0.11175660789012909,
                134.0,
                327.0,
                0.18920457363128662,
                133.0,
                318.0,
                0.03496965393424034,
                134.0,
                321.0,
                0.06728111952543259,
                134.0,
                322.0,
                0.03228085860610008,
                134.0,
                327.0,
                0.06891388446092606,
                129.0,
                319.0,
                0.0491134412586689,
                131.0,
                323.0,
                0.07113371789455414,
                130.0,
                325.0,
                0.07127388566732407,
                130.0,
                326.0,
                0.055080581456422806,
                128.0,
                319.0,
                0.15777651965618134,
                128.0,
                322.0,
                0.14866244792938232,
                128.0,
                324.0,
                0.10689514130353928,
                128.0,
                325.0,
                0.11851004511117935,
                126.0,
                319.0,
                0.14580543339252472,
                126.0,
                321.0,
                0.16165511310100555,
                126.0,
                324.0,
                0.13734498620033264,
                126.0,
                324.0,
                0.19786761701107025
            ],
            "face_kpts": [
                158.922,
                241.77,
                1.0,
                158.37,
                243.699,
                1.0,
                157.841,
                245.634,
                1.0,
                157.461,
                247.602,
                1.0,
                157.518,
                249.6,
                1.0,
                158.049,
                251.526,
                1.0,
                159.005,
                253.287,
                1.0,
                160.28,
                254.835,
                1.0,
                161.827,
                256.107,
                1.0,
                163.641,
                256.935,
                1.0,
                165.558,
                256.614,
                1.0,
                166.861,
                255.1,
                1.0,
                168.212,
                253.618,
                1.0,
                169.624,
                252.195,
                1.0,
                170.896,
                250.647,
                1.0,
                171.819,
                248.868,
                1.0,
                172.717,
                247.076,
                1.0,
                165.392,
                244.78,
                1.0,
                166.544,
                244.713,
                1.0,
                167.668,
                244.822,
                1.0,
                168.779,
                245.005,
                1.0,
                169.832,
                245.318,
                1.0,
                171.926,
                245.925,
                1.0,
                172.304,
                245.981,
                1.0,
                172.634,
                246.018,
                1.0,
                172.967,
                246.036,
                1.0,
                173.246,
                246.256,
                1.0,
                170.673,
                246.827,
                1.0,
                170.604,
                248.239,
                1.0,
                170.493,
                249.632,
                1.0,
                170.339,
                251.012,
                1.0,
                167.345,
                250.726,
                1.0,
                167.951,
                251.197,
                1.0,
                168.673,
                251.562,
                1.0,
                169.335,
                251.798,
                1.0,
                170.028,
                251.537,
                1.0,
                166.289,
                245.748,
                1.0,
                167.076,
                245.864,
                1.0,
                167.872,
                245.867,
                1.0,
                168.604,
                246.143,
                1.0,
                167.815,
                246.175,
                1.0,
                167.047,
                245.98,
                1.0,
                171.323,
                246.884,
                1.0,
                171.704,
                246.981,
                1.0,
                172.07,
                247.119,
                1.0,
                172.347,
                247.39,
                1.0,
                171.976,
                247.289,
                1.0,
                171.64,
                247.102,
                1.0,
                163.632,
                251.864,
                1.0,
                165.519,
                252.181,
                1.0,
                167.402,
                252.696,
                1.0,
                167.835,
                252.884,
                1.0,
                168.108,
                253.058,
                1.0,
                168.303,
                253.374,
                1.0,
                168.178,
                253.664,
                1.0,
                167.745,
                254.079,
                1.0,
                167.25,
                254.431,
                1.0,
                166.561,
                254.539,
                1.0,
                165.303,
                253.952,
                1.0,
                164.295,
                253.025,
                1.0,
                163.788,
                251.971,
                1.0,
                165.602,
                252.614,
                1.0,
                167.442,
                253.29,
                1.0,
                167.766,
                253.557,
                1.0,
                168.069,
                253.671,
                1.0,
                167.507,
                253.821,
                1.0,
                166.871,
                253.762,
                1.0,
                165.18,
                253.093,
                1.0
            ],
            "face_valid": true,
            "lefthand_valid": true,
            "righthand_valid": true,
            "foot_valid": false,
            "foot_kpts": [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0
            ]
        }
    ],
    "categories": [
        {
            "supercategory": "person",
            "id": 1,
            "name": "person",
            "keypoints": [
                "nose",
                "left_eye",
                "right_eye",
                "left_ear",
                "right_ear",
                "left_shoulder",
                "right_shoulder",
                "left_elbow",
                "right_elbow",
                "left_wrist",
                "right_wrist",
                "left_hip",
                "right_hip",
                "left_knee",
                "right_knee",
                "left_ankle",
                "right_ankle"
            ],
            "skeleton": [
                [
                    16,
                    14
                ],
                [
                    14,
                    12
                ],
                [
                    17,
                    15
                ],
                [
                    15,
                    13
                ],
                [
                    12,
                    13
                ],
                [
                    6,
                    12
                ],
                [
                    7,
                    13
                ],
                [
                    6,
                    7
                ],
                [
                    6,
                    8
                ],
                [
                    7,
                    9
                ],
                [
                    8,
                    10
                ],
                [
                    9,
                    11
                ],
                [
                    2,
                    3
                ],
                [
                    1,
                    2
                ],
                [
                    1,
                    3
                ],
                [
                    2,
                    4
                ],
                [
                    3,
                    5
                ],
                [
                    4,
                    6
                ],
                [
                    5,
                    7
                ]
            ]
        }
    ]
}
