### ISSUE TITLE
Add cvat-cli to PyPI

### ISSUE THREAD

**Issue by zhiltsov-max** [openvinotoolkit/cvat#3848] opened 2021-11-01 10:03 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour

A suggestion from the Gitter chat. Basically, be able to `pip install cvat-cli`.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by christian-steinmeyer** [comment] 2021-11-11 14:37
duplicate of https://github.com/openvinotoolkit/cvat/issues/3716

**Comment by nmanovic** [comment] 2021-11-19 19:24
I will close the issue because we already have one.

**Closed by nmanovic** 2021-11-19 19:24 UTC
Labels: duplicate, enhancement
