### ISSUE TITLE
 Why the observer role can edit the tasks?

### ISSUE THREAD

**Issue by ErnestoGranadillo1** [openvinotoolkit/cvat#1906] opened 2020-07-15 19:05 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment] 2020-07-17 13:39
@ErnestoGranadillo1 Hi, please don't ignore the issue template.
I cannot reproduce your issue on the last develop branch, so please please fill all template fields and specify the steps to reproduce.

**Comment by ErnestoGranadillo1** [comment] 2020-07-17 13:46
My problem is that in Cvat there is a Profile or user role called Observer, that profile according to what I have read can only see the tasks and project that are being carried out but it should not be edited.

The problem is that in my Cvat that profile if you can edit and I can not get how to only observe and do not edit.

**Comment by azhavoro** [comment] 2020-07-17 14:35
I understand your problem.
A user with only one `observer` role should not edit a task unless a task has been assigned to this user.

**Comment by bsekachev** [comment] 2020-09-21 11:27
I will close the issue since there aren't any response from you. 
Please, do not hesitate reopen if you are still experiencing it.

**Closed by bsekachev** 2020-09-21 11:27 UTC
Labels: question
