### ISSUE TITLE
Could not create task. IsADirectoryError

### ISSUE THREAD

**Issue by bigred94** [openvinotoolkit/cvat#2250] opened 2020-10-01 18:07 UTC
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I connected an MinIO Sever as a file share and when I try to create a task with a lot of images (~15k) the task spins for couple minutes then fails to be created with the following error messages.

<img width="1532" alt="Screen Shot 2020-10-01 at 12 12 23 PM" src="https://user-images.githubusercontent.com/69821298/94846235-6a8e3c80-03e6-11eb-9ae2-e9618918d2b1.png">

It seems to be complaining that there is a a subdirectory but I double checked and the directory I selected only contains jpgs.  

### Expected Behaviour

Create task without any issues. Even if there was a subdirectory I would expect it to search through it for more images and not fail.
### Current Behaviour

See image above. I have confirmed that other smaller directories work and similarly large directories fail.
### Steps to Reproduce (for bugs)

1. Attach file share.
1. Try to import a large amount of data. 20k+ images.
1.
1.

### Context

Cannot create large tasks.
### Your Environment

- Git hash commit (`git log -1`): 7f73f5e3184ffa0ad1beafa4b87a38031ce65e48
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment] 2020-10-05 07:31
@Marishka17 Could you please take a look?

**Comment by Marishka17** [comment] 2020-10-05 14:44
@bigred94, hi, it seems to me the problem was solved a few pull requests ago.
Can you update your CVAT version and check if the problem is still there? 
Also, can you attach the logs? (`docker logs cvat`)
Until then, let me close this issue.

**Comment by bigred94** [comment] 2020-10-05 20:24
@Marishka17 @nmanovic I've pulled the latest changes and no longer have this issue. The task was created just fine. Thanks!

**Closed** 2020-10-06 11:41 UTC
Labels: bug

**Comment by timiil** [comment] 2021-09-03 08:03
hello , i click this error again, when i import a task zip. if i use 7zip make this zip file, it show this failed, if i use windows zip command to make the file, it is ok. FYI, my CVAT version is :

Server version: 1.5

Core version: 3.13.3

Canvas version: 2.5.0

UI version: 1.21.1

**Comment by azhavoro** [comment] 2021-09-03 08:06
> hello , i click this error again, when i import a task zip. if i use 7zip make this zip file, it show this failed, if i use windows zip command to make the file, it is ok. FYI, my CVAT version is :
> 
> Server version: 1.5
> 
> Core version: 3.13.3
> 
> Canvas version: 2.5.0
> 
> UI version: 1.21.1

Hi, please submit a new issue

**Comment by timiil** [comment] 2021-09-03 08:08
> 
> 
> > hello , i click this error again, when i import a task zip. if i use 7zip make this zip file, it show this failed, if i use windows zip command to make the file, it is ok. FYI, my CVAT version is :
> > Server version: 1.5
> > Core version: 3.13.3
> > Canvas version: 2.5.0
> > UI version: 1.21.1
> 
> Hi, please submit a new issue

sure

**Comment by mikeyEcology** [comment] 2021-11-09 12:00
I got this error, but then I substantially reduced the number of images in my task and it worked.
