### ISSUE TITLE
ERROR: Service 'cvat_ui' failed to build: The command '/bin/sh -c npm ci' returned a non-zero code: 1

### ISSUE THREAD

**Issue by vikram1995** [openvinotoolkit/cvat#3864] opened 2021-11-03 11:28 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

Step 20/34 : RUN npm ci
 ---> Running in e21f924842cd
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated eslint-config-typescript-recommended@1.4.17: Use eslint-plugin-typescript version >= 1.0.0
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /tmp/cvat-canvas/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /tmp/cvat-canvas/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/tmp/cvat-canvas/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/tmp/cvat-canvas/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/cvat-canvas/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Linux 3.10.0-957.el7.x86_64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/tmp/cvat-canvas/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /tmp/cvat-canvas/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-03T11_17_17_642Z-debug.log
ERROR: Service 'cvat_ui' failed to build: The command '/bin/sh -c npm ci' returned a non-zero code: 1

### Steps to Reproduce (for bugs)

1. git clone -b master https://github.com/openvinotoolkit/cvat.git
2. docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment] 2021-11-03 13:58
Which CVAT release do you use? Please try the latest develop. It should be fixed.

**Comment by vikram1995** [comment] 2021-11-08 04:15
v1.6.0

**Comment by nmanovic** [comment] 2021-11-08 05:38
@azhavoro , @ActiveChooN ,

Could you please comment?

**Comment by azhavoro** [comment] 2021-11-08 07:42
Duplicate of https://github.com/openvinotoolkit/cvat/issues/3853, @vikram1995 Please try to use develop branch

**Closed** 2021-11-08 08:42 UTC
Labels: duplicate
