### ISSUE TITLE
User project settings are not saved

### ISSUE THREAD

**Issue by nstolyarov** [openvinotoolkit/cvat#2957] opened 2021-03-16 11:20 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

After each entering next job all project settings (such as autosave settings, image quality, transparency, etc.) are reset to their default values.

### Expected Behaviour
Every time you sign in CVAT starts with user settings instead of default and keeps it unchanged during all jobs.

### Current Behaviour
Every time you starting new job CVAT resets settings to default one.

### Possible Solution
Save settings to user DB (reddis I guess), load it on every sign in and keep it in all jobs.

### Context
CVAT is running a large project and it is very inconvenient to set the 
settings every time you start new job

### Your Environment
- Git hash commit (`git log -1`): commit 7a2dcfff61626dbfdaa694127fc1cff8ee10e000 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <anastasia.yasakova@intel.com>
Date:   Tue Mar 9 10:41:33 2021 +0300
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): GNU/Linux Ubuntu
4.15.0-136-generic
x86_64
- Settings screenshot attached
![settings](https://user-images.githubusercontent.com/80746178/111300960-b403d880-8662-11eb-9f41-4fe592b3fcf6.png)

**Comment by azhavoro** [comment] 2021-03-16 16:04
Duplicate of #1209

**Comment by bsekachev** [comment] 2021-03-16 16:23
@nstolyarov 

Please, refer to original issue. 
We do not need duplicate it. 
Just add a reaction or a comment (it would help us to understand what features are most demanded)

**Closed by bsekachev** 2021-03-16 16:23 UTC
Labels: duplicate
