### ISSUE TITLE
Label classes are not sorted in dropdown

### ISSUE THREAD

**Issue by valeriyvan** [openvinotoolkit/cvat#2695] opened 2021-01-20 19:23 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

User expect label classes to be sorted. But they are "nearly sorted" or "some time not sorted".

<img width="681" alt="Screenshot 2021-01-20 at 20 12 56" src="https://user-images.githubusercontent.com/1630974/105223750-78fe9080-5b5c-11eb-9e05-c8ebf8473cc9.png">

### Steps to Reproduce (for bugs)
Create a task with several dozens of label classes. Try to label data.

### Your Environment

- Git hash commit (`git log -1`): commit 226c2f286b8a8745365f78f1ba10f6481d6a85f5 
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20
- Code example or link to GitHub repo or gist to reproduce problem: n/a
- Other diagnostic information / logs: n/a

### Next steps
Related to issue #2636. But I believe it's related, but different issue.

**Comment by bsekachev** [comment] 2021-01-21 06:13
Hi @valeriyvan 

>> User expect label classes to be sorted

It is not exactly true. There are open issues in the list where people expect to see labels in order of adding, without any sorting. I suppose it is a right approach to sutisfly also your request. You can sort the list on your own and push them in any order you need.

**Comment by valeriyvan** [comment] 2021-01-21 07:18
Sounds like we need a setting how to show labels: in order how they appear or sorted.

**Comment by bsekachev** [comment] 2021-01-21 11:05
There are different kinds of sorting (alphabetical, numeric, others custom). Support of them is not an option for CVAT. As I mentioned keeping ordering as labels appears (related #2636) would cover all the cases. 

I will close this issue.

**Closed by bsekachev** 2021-01-21 11:05 UTC

**Comment by valeriyvan** [comment] 2021-01-21 21:17
> There are different kinds of sorting (alphabetical, numeric, others custom). Support of them is not an option for CVAT. As I mentioned keeping ordering as labels appears (related #2636) would cover all the cases.
> 
> I will close this issue.

Because different kinds of sorting options exist, it was decided not to sort at all. Bad(

**Comment by nmanovic** [comment] 2021-01-22 08:17
@valeriyvan , if you have a good proposal how to implement it in UI, please do that. We are happy to accept any PRs with great features which are necessary for our community. Here you report a bug. It is not a bug, it was made intentionally by requests.
