### ISSUE TITLE
Can´t run CVAT after adding analytics on WindowsFound orphan containers (cvat_logstash, cvat_elasticsearch, cvat_kibana, cvat_kibana_setup) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.

### ISSUE THREAD

**Issue by giorginagonzalez** [openvinotoolkit/cvat#1868] opened 2020-07-08 19:45 UTC
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Expected Behaviour

I have cvat built on my windows 10 device. After I put the commands shown in the docummentation to install aanalytics (https://github.com/opencv/cvat/blob/develop/components/analytics/README.md) I can´t access to my cvat and show the messages that you see in my attach file.

![error_cvat_analytics1](https://user-images.githubusercontent.com/19914765/86962522-0fbfae80-c131-11ea-95bf-bd2beccac05b.jpg)

Besides, when I up the docker-compose, I see this message:
### Found orphan containers (cvat_logstash, cvat_elasticsearch, cvat_kibana, cvat_kibana_setup) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.

If I delete those orphan containers and re-build cvat, I can access as usual without analytics.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):19.03.5
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment] 2020-07-08 20:51
Hi, what is exact commands do you use to build and up cvat with analitics?

**Comment by giorginagonzalez** [comment] 2020-07-08 21:02
Hi, 

# From project root directory
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml build

# From project root directory
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d

**Comment by azhavoro** [comment] 2020-07-10 06:53
Please specify CVAT version, also provide logs from cvat and cvat_proxy container: `docker logs cvat_proxy > proxy.log`, `docker log cvat > cvat.log` .

**Comment by giorginagonzalez** [comment] 2020-07-14 02:43
**docker logs cvat_proxy > proxy.log**

2020/07/08 19:56:03 [error] 8#8: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /api/v1/users/self HTTP/1.1", upstream: "http://172.21.0.7:8080/api/v1/users/self", host: "localhost:8080", referrer: "http://localhost:8080/auth/login"
2020/07/08 19:56:19 [error] 8#8: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /api/v1/restrictions/user-agreements HTTP/1.1", upstream: "http://172.21.0.7:8080/api/v1/restrictions/user-agreements", host: "localhost:8080", referrer: "http://localhost:8080/auth/login"

**docker log cvat > cvat.log**

Unlinking stale socket /tmp/supervisord/supervisor.sock
Unlinking stale socket /tmp/supervisord/supervisor.sock

![Screenshot_1](https://user-images.githubusercontent.com/19914765/87377699-30856b00-c55a-11ea-8cab-f5d3cb48b3fc.jpg)

**Comment by azhavoro** [comment] 2020-07-14 06:56
Looks like smth wrong with cvat container, please do the following steps:
1. `docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml down`
2. `docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up`
3. wait some time, save the output from the previous command and attach this file

**Comment by giorginagonzalez** [comment] 2020-07-14 18:24
[Logs.txt](https://github.com/opencv/cvat/files/4920506/Logs.txt)

I have deleted and re-installed several times CVAT but I realized the user, tasks and all information doesn´t delete. Would be this a cause?

**Comment by azhavoro** [comment] 2020-07-15 06:45
All data stored in docker volumes, I suppose it cannot be the cause of your issue.
According your logs cvat backend server is started correctly, but for some reason start takes about 6 min(16:10:04 - first log event, 16:16:16 - time when cvat is ready). At this time you will get 502 error.

Could you collect logs one more time without analytics?
1. `docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml down`
2 . `docker-compose -f docker-compose.yml build`
3. `docker-compose -f docker-compose.yml up`
4. wait about 10 min, save the output from the previous command and attach this file
Thanks!

**Comment by giorginagonzalez** [comment] 2020-07-17 05:12
[logs_whitout_annalytics.txt](https://github.com/opencv/cvat/files/4935838/logs_whitout_annalytics.txt)

Thank you.

**Comment by azhavoro** [comment] 2020-07-28 14:07
@giorginagonzalez Can this problem may be related with your disk performance? Could you please monitor disk load during CVAT startup process in first case?

**Comment by lolpa1n** [comment] 2021-09-06 14:11
Same error

**Comment by nmanovic** [comment] 2021-11-26 07:26
@lolpa1n , I will close the issue as outdated. If you still have the problem, please reopen and provide more information.

**Closed by nmanovic** 2021-11-26 07:26 UTC
