### ISSUE TITLE
minimal reproducible compose configuration, device_requests param is not supported in API versions < 1.40

### ISSUE THREAD

**Issue by YSUN-coder** [openvinotoolkit/cvat#3011] opened 2021-03-25 04:13 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
Hi, I have problem to install cvat in Ubuntu. After following the instruction, I meet the problem as follow. Could I have some suggestions?

### Your Environment

- Git hash commit (`git log -1`): c58074ea1f6337a0e0747af5298b86b85fc577e3
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.5
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
$ docker-compose up
Creating network "cvat_default" with the default driver
Creating cvat_redis ...
Creating cvat_db    ...

ERROR: for cvat_redis  device_requests param is not supported in API versions < 1.40

ERROR: for cvat_db  device_requests param is not supported in API versions < 1.40

ERROR: for cvat_redis  device_requests param is not supported in API versions < 1.40

ERROR: for cvat_db  device_requests param is not supported in API versions < 1.40
Traceback (most recent call last):
  File "/home/mmadmin/.local/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.26.0.dev0', 'console_scripts', 'docker-compose')())
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/cli/main.py", line 1103, in up
    cli=native_builder,
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/project.py", line 573, in up
    get_deps,
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/project.py", line 559, in do
    renew_anonymous_volumes=renew_anonymous_volumes,
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/service.py", line 548, in execute_convergence_plan
    scale, detached, start
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/service.py", line 469, in _execute_convergence_create
    "Creating"
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/service.py", line 467, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/service.py", line 455, in create_and_start
    container = service.create_container(number=n, quiet=True)
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/service.py", line 338, in create_container
    previous_container=previous_container,
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/service.py", line 918, in _get_container_create_options
    one_off=one_off)
  File "/home/mmadmin/.local/lib/python3.6/site-packages/compose/service.py", line 1059, in _get_container_host_config
    device_requests=device_requests,
  File "/home/mmadmin/.local/lib/python3.6/site-packages/docker/api/container.py", line 595, in create_host_config
    return HostConfig(*args, **kwargs)
  File "/home/mmadmin/.local/lib/python3.6/site-packages/docker/types/containers.py", line 639, in __init__
    raise host_config_version_error('device_requests', '1.40')
docker.errors.InvalidVersion: device_requests param is not supported in API versions < 1.40

**Comment by azhavoro** [comment] 2021-03-25 06:34
Hi, what is output of `docker version`?

**Comment by YSUN-coder** [comment] 2021-03-26 02:25
Docker version 20.10.5

> Hi, what is full output of `docker version`?

**Comment by azhavoro** [comment] 2021-03-26 09:15
I would suggest creating an issue in the docker-compose repository with a minimal reproducible compose configuration.

**Comment by nmanovic** [comment] 2021-04-15 05:27
@YSUN-coder , it looks like an issue with docker and docker-compose on your system. I don't think we can help with the issue. It is first time when meet the issue. I will close it for now. Please let us know if you find a solution.

**Closed by nmanovic** 2021-04-15 05:27 UTC
