### ISSUE TITLE
Newly created account should need approval before user can log in

### ISSUE THREAD

**Issue by valeriyvan** [openvinotoolkit/cvat#2702] opened 2021-01-21 21:09 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Currently when new user creates account, it immediately can log in and see project, tasks, etc. It is absolutely no go! This configuration makes CVAT impossible to be used on publicly accessible server.

### Expected Behaviour

New user shouldn't be possible to login until account is approved by administrator or superuser.

### Current Behaviour

New user creates account and logs in and see all project internal. Any malicious user could register!
 

### Possible Solution

Provide account approval flow.

### Steps to Reproduce (for bugs)

Create account over Create account link from login page and then login to see project, tasks, etc.

### Context

n/a

### Your Environment

- Git hash commit (`git log -1`): 226c2f2
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? n/a
- Operating System and version (e.g. Linux, Windows, MacOS): n/a
- Code example or link to GitHub repo or gist to reproduce problem: n/a
- Other diagnostic information / logs: n/a

### Next steps

n/a

**Comment by bsekachev** [comment] 2021-01-22 08:00
Duplicate of #1030, as a workaround please use the parameter 'reduce_task_visibility' (now is on line 437) in ``base.py`` as Andrey suggested.

**Closed by bsekachev** 2021-01-22 08:00 UTC

**Comment by omersefaztrk** [comment] 2021-05-06 09:54
@bsekachev @valeriyvan I did this process but i does not work. I didnt understand why? After ı changed `reduce_task_visibility` as True, ı rebuilded cvat using `docker-compose up -d`. However no change. I mean that ı can not build changing of reduce_task_visibility. I think there is something ı dont know.

**Comment by azhavoro** [comment] 2021-05-06 10:01
@omersefaztrk Answered you in the other issue, `docker-compose up -d` doesn't build images, you should use  `--build` flag :`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`. Please read the docker-compose documentation or our installation guide.

**Comment by omersefaztrk** [comment] 2021-05-06 12:10
Thanks. It works
