### ISSUE TITLE
instances' order of a label changes randomly

### ISSUE THREAD

**Issue by ZhH-17** [openvinotoolkit/cvat#3191] opened 2021-05-14 12:39 UTC
There is only a label in my job, by I want the instances sorted as I expect, for example, by time or whatever.
But I cannot achieve it in CVAT, after add new instance and close, order changes when reopen the task.

At begin, 1 is here
![tmp](https://user-images.githubusercontent.com/33834729/118271789-52da7300-b4f4-11eb-9707-98170ba588f0.png)
After I add a instance, poition of 1 changes
![tmp1](https://user-images.githubusercontent.com/33834729/118272063-a64cc100-b4f4-11eb-96e6-9ee3e18f1e28.png)

It's not sorted by adding time reversely.

**Comment by bsekachev** [comment] 2021-05-14 13:53
Hi @ZhH-17 

I am not sure I understand your steps to reproduce. In particular if you create objects and save them, then reopen a task,  and create one more object, it can't have id 1 because the id is already exist. 

Speaking about IDs.. IDs that you see are client IDs. They are actually relevant only during one session. Each saved on the server object also has server ID (you can't find it in client because it is internal). Such a scheme with different types of IDs exist to be able to work on one job in parallel and to minimize number of interactions with the server (in other case each new object would require a server request). 

At the top right corner you can see Sort by (id ascent, id descent, time changed). These sortings use client IDs, and client time changing. The latest also is not stored in the server database. 

One simple solution I could suggest is to add sorting options (server ID ascent, server ID descent). But I am not sure it will help you, please suggest if it will.

**Comment by ZhH-17** [comment] 2021-05-18 03:50
@bsekachev Thanks for your answer.
I am not familiar with client IDs or server IDs. But sorting options can't help me, it only change in view, not ID of the instances. When I download annotations, annotations ID will not change.

BTW, let me add a explanation ot my question. I have different color cards, if I label them with the same label, can they have specific order as I want? For example, red is instance 1, blue is instance 2 ...

**Comment by bsekachev** [comment] 2021-05-18 08:48
@ZhH-17 

> BTW, let me add a explanation ot my question. I have different color cards, if I label them with the same label, can they have specific order as I want? For example, red is instance 1, blue is instance 2 ...

> I am not sure I really understand your use case. You can't bind ID to a color, what is more color is not a constant. If you remove for example an object with ID 1, then reopen the task, you will see, that all colors are shifted by one. It is because instance's colors are UI only (they are not stored in the database and aren't dumped to annotations file), they are set automatically based on hard-coded enum ``cvat/cvat-core/src/enums.js`` (colors enum) when objects are being imported from the server.

If you want to see some colors binded to instances, you can add a label attribute (text, or select types) "color" and setup color for each an object

**Comment by bsekachev** [comment] 2021-06-08 13:08
I hope my explanation helped you somehow. I will close the issue because I do not see a specific bug or feature request here. Do not hesitate to reopen it if you have any ideas.

**Closed by bsekachev** 2021-06-08 13:08 UTC
