### ISSUE TITLE
Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by rnekk2** [openvinotoolkit/cvat#1823] opened 2020-06-30 09:13 UTC
We are getting this error quire often. It is happening while loading new images during annotations.

TypeError
Cannot read property 'label' of undefined

TypeError: Cannot read property 'label' of undefined
    at Function.mapToProps (http://192.169.1.10:5000/cvat-ui.min.js:72:1476716)
    at a (http://192.168.1.10:5000/cvat-ui.min.js:72:1100333)
    at Function.a.mapToProps (http://192.168.1.10:5000/cvat-ui.min.js:72:1100469)
    at a (http://192.168.1.10:5000/cvat-ui.min.js:72:1100333)
    at http://192.168.1.10:5000/cvat-ui.min.js:72:1101688
    at http://192.168.1.10:5000/cvat-ui.min.js:72:1098712
    at Object.useMemo (http://192.168.1.10:5000/cvat-ui.min.js:43:63498)
    at useMemo (http://192.168.1.10:5000/cvat-ui.min.js:35:5228)
    at p (http://192.168.1.10:5000/cvat-ui.min.js:72:1098656)
    at ui (http://192.168.1.10:5000/cvat-ui.min.js:43:59331)

**Comment by bsekachev** [comment] 2020-06-30 10:54
@rnekk2 

Please, follow the issue template. Need to specify versions and stable way to reproduce.

**Comment by rnekk2** [comment] 2020-07-03 16:05
Not coming after latest pull.

**Comment by azhavoro** [comment] 2020-07-07 10:50
The issue still exists for commit 18f6b2f95d0bcd0a491ad3f7a892fabb734f7b00.

**Comment by bsekachev** [comment] 2020-08-16 18:52
The issue appears regularly. Need to understand steps to reproduce. If anyone can help, you are welcome

**Comment by zmfkzj** [comment] 2020-10-07 09:10
The issue still exists

**Comment by bsekachev** [comment] 2020-10-07 10:18
@zmfkzj 
Yes, we know. And we know exact place where the error occurs, but it is not clear what leads to this state.

**Comment by bsekachev** [comment] 2020-10-12 16:09
I still wasn't able to reproduce the bug, but according to the code it looks like that mapStateToProps is called for a connected child before rerendering of a connected parent. Just rewrited code in #2311 what could fix the issue for us.

**Comment by bsekachev** [comment] 2020-10-13 14:36
Let's close the issue. If it appear after the fix above, I'll reopen it.

**Comment by bsekachev** [comment] 2020-10-28 09:00
Looks like the issue still appears sometimes on ``cvat.org``. Need to investigate more..

**Closed** 2020-11-17 10:34 UTC
Labels: bug
