### ISSUE TITLE
Auto Annotation Mack RCNN error 

### ISSUE THREAD

**Issue by SabinaUS** [openvinotoolkit/cvat#4021] opened 2021-12-14 04:09 UTC
Hello, everyone when I try to add Mask RCNN trained model using gpu to the auto annotation process it is gives error as unhealthy. 
And docker output is :
21.12.14 03:59:20.166 sor.http.w0.python.logger (D) Running wrapper {"command": "/usr/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-c6s1d60l2j1nqsluft90.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger"}
l{"datetime": "2021-12-14 03:59:21,337", "level": "error", "message": "Caught unhandled exception while initializing", "with": {"err": "expected str, bytes or os.PathLike object, not NoneType", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 350, in run_wrapper\n    args.trigger_name)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 57, in __init__\n    self._entrypoint = self._load_entrypoint_from_handler(handler)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 159, in _load_entrypoint_from_handler\n    module = __import__(module_name)\n  File \"/opt/nuclio/main.py\", line 5, in <module>\n    from model_loader import ModelLoader\n  File \"/opt/nuclio/model_loader.py\", line 10, in <module>\n    MASK_RCNN_DIR = os.path.abspath(os.environ.get('/home/user/Desktop/Mask_RCNN-master/'))\n  File \"/usr/lib/python3.6/posixpath.py\", line 378, in abspath\n    path = os.fspath(path)\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n", "worker_id": "0"}}
21.12.14 03:59:21.520 sor.http.w0.python.logger (E) Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 0 exited unexpectedly with: exit status 1

goroutine 82 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc0002ec000)
	/nuclio/pkg/processor/runtime/rpc/abstract.go:464 +0x576
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper
	/nuclio/pkg/processor/runtime/rpc/abstract.go:236 +0x1b5

**Comment by azhavoro** [comment] 2021-12-17 09:30
Duplicate of #4004

**Closed by azhavoro** 2021-12-17 09:30 UTC
