### ISSUE TITLE
av library issue...

### ISSUE THREAD

**Issue by KALALRANJITHKUMAR** [openvinotoolkit/cvat#3342] opened 2021-06-17 15:12 UTC
every time it is required to install the library manually using **pip install av** , please look into this. if we dont install it we are facing issues while running manage.py file.

**Comment by bsekachev** [comment] 2021-06-17 20:57
@azhavoro Could you please look at the issue?

**Comment by azhavoro** [comment] 2021-06-18 07:05
@KALALRANJITHKUMAR Hi,
Please don't ignore the issue template, please provide error messages and exact steps to reproduce. `av` is one of the many CVAT dependencies, and currently I can't figure out why you need to reinstall if this package is already installed.

**Comment by bsekachev** [comment] 2021-07-26 08:52
I will close the issue, because there is not a response from your side. Please, do not hesitate to reopen it if you still have questions and ready to provide more details.

**Closed by bsekachev** 2021-07-26 08:52 UTC
Labels: need info
