### ISSUE TITLE
CVAT Attribute Selection Raises Error

### ISSUE THREAD

**Issue by markl21** [openvinotoolkit/cvat#2554] opened 2020-12-09 20:34 UTC
### My actions before raising this issue
-  Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
-  Searched [past issues](/issues)
- Installed CVAT in Google Cloud Compute Engine

### Expected Behaviour
When selecting an attribute for an annotation label, the label should take on selected attribute

### Current Behaviour
When selecting an attribute, an error is raised for certain labels pictured
![cvat_attribute_error](https://user-images.githubusercontent.com/60868184/101683860-88ee6500-3a33-11eb-998b-b175bb02881f.PNG)

### Possible Solution
Workaround is switching to another label and switching back to the desired label. Attribute selection works then.
![cvat_benign_switch](https://user-images.githubusercontent.com/60868184/101683938-a58a9d00-3a33-11eb-9e83-8df579cb4533.PNG)
![cvat_tumor_works_wth](https://user-images.githubusercontent.com/60868184/101683944-a7546080-3a33-11eb-8d2d-ad97634b63ce.PNG)

### Steps to Reproduce (for bugs)

1. create task with labels with attributes
2. Attempt to annotate with label, then add attribute to label.

### Your Environment

- Ubuntu 18.04
- Docker version `docker version` (e.g. Docker: latest):
- Are you using Docker Swarm or Kubernetes? No

**Comment by bsekachev** [comment] 2020-12-10 06:58
@markl21 Could you please send us attribute specification? 
To do it click "Copy" button and then paste in the issue

![Screenshot from 2020-12-10 09-57-27](https://user-images.githubusercontent.com/40690378/101732369-272f0900-3ace-11eb-8ce3-796061ba5be2.png)

**Comment by bsekachev** [comment] 2020-12-10 07:17
@markl21 

Also it would be useful if you attached CVAT version (top right menu -> about) and git commit hash.

**Comment by bsekachev** [comment] 2020-12-28 09:30
There is not answer and I cannot reproduce the issue. So, I will close it. Do not hesitate reopen it if you have additional information.

**Closed by bsekachev** 2020-12-28 09:30 UTC
