### ISSUE TITLE
IOG throws errors, won't work on localhost

### ISSUE THREAD

**Issue by davodogster** [openvinotoolkit/cvat#2828] opened 2021-02-18 04:20 UTC
### My actions before raising this issue
Deploy Complete:
![image](https://user-images.githubusercontent.com/46079516/108304366-c5e18f80-720c-11eb-8fc6-64e308d14292.png)

![image](https://user-images.githubusercontent.com/46079516/108304430-e578b800-720c-11eb-8db5-3abf4bed193f.png)

![image](https://user-images.githubusercontent.com/46079516/108304743-86677300-720d-11eb-9ac2-627e4247aae2.png)

I'm running cvat and nuctl in WSL2

### Expected Behaviour
IOG Works and auto segments

### Current Behaviour
Throws these errors:

![image](https://user-images.githubusercontent.com/46079516/108304676-63d55a00-720d-11eb-8e00-3cde37354c26.png)

Some of the nuclio pre trained models inside CVAT have worked for me before so that is not the issue.

Are you able to please fix this?

Cheers,

Sam

EDIT: It throws the same error when I deploy CVAT on localhost 8080 (instead of 7080) I just tried it.

**Comment by nmanovic** [comment] 2021-02-18 05:15
@davodogster , could you please send me logs of the IOG container? In the screenshot it is c3121fe...

**Comment by davodogster** [comment] 2021-02-18 20:17
@nmanovic Hope this helps. Let me know if you need anymore info.

![image](https://user-images.githubusercontent.com/46079516/108416264-55318600-7293-11eb-94a3-d7ab12958ea7.png)

**Comment by nmanovic** [comment] 2021-02-20 07:55
@davodogster , the error is shown in logs:

```
No such file or directory: .../IOG_PASCAL_SBD.pth
```

At the same time I see that in your first message the build was successful. Could you please run commands below?

```
docker exec -it c3121fe bash
cd /opt/nuclio/iog
du -h IOG_PASCAL_SBD.pth
conda activate iog
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}"
echo "/download/ {print \$NF}" > confirm_code.awk
curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk -f confirm_code.awk ./cookie`&id=${fileid}" -o ${filename}
du -h IOG_PASCAL_SBD.pth
``` 

Send all logs after commands above. The code above has to download IOG_PASCAL_SBD.pth from google drive. I believe on your machine it will fail silently.

**Comment by davodogster** [comment] 2021-02-21 20:28
Hi @nmanovic 

The Container just keeps restarting so I am unable to bash into it. (That was a docker images command above, not docker container ls)
![image](https://user-images.githubusercontent.com/46079516/108637197-80fc7800-74ee-11eb-8909-e4128a777276.png)

I will note that I had to use the curl "-k" arg for the model download in the .yaml file because otherwise I cannot download the .pth model due to a firewall/block.

Output on container deployment
![image](https://user-images.githubusercontent.com/46079516/108637626-4e537f00-74f0-11eb-8b3c-ea22a184b0ae.png)

**Comment by nmanovic** [comment] 2021-02-22 19:53
@davodogster , does it mean that you solve the problem using '-k' argument? Unfortunately, firewall is a complex topic. I'm not sure that we can solve it somehow (insecure connection isn't a valid solution for mainstream code). Do you have any common solutions in your mind which will cover your case as well?

**Comment by davodogster** [comment] 2021-02-23 20:03
hi @nmanovic I have to use -k to get the curl command to work, and the container to deploy, but it doesn't fix everything because the container just keeps restarting when I deploy it and it gives the error logs that I attached above.

**Comment by davodogster** [comment] 2021-03-01 03:01
Hi @nmanovic 
Now I can get the container running and not restarting, But in the CVAT tool it still gives the same error as previously.

![image](https://user-images.githubusercontent.com/46079516/109446654-f647ea00-7aa6-11eb-9000-a61358b18531.png)

![image](https://user-images.githubusercontent.com/46079516/109446715-0d86d780-7aa7-11eb-82c6-1d3694037ca8.png)

Nuclio is running here:
![image](https://user-images.githubusercontent.com/46079516/109446762-28594c00-7aa7-11eb-8bdb-838854c67bd7.png)

There are no logs this time (I checked in docker desktop)

**Comment by fjean** [comment] 2021-03-11 16:53
Any development on this issue? I have the same issue, and I found out that the error "Request failed with status code 500" happens because there is an exception `KeyError` in `cvat/serverless/pytorch/shiyinzhang/iog/nuclio/main.py` for the line `pos_points = data["pos_points"]`, there is no key `pos_points`. After verification, the only keys in `data` are `points` and `image`.

**Comment by nmanovic** [comment] 2021-03-11 18:10
@fjean , you need to update your instance till develop version. 

```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
docker-compose up -d
```

**Comment by davodogster** [comment] 2021-03-18 01:14
@nmanovic and what about me?

**Comment by yongun414** [comment] 2021-03-18 04:39
@davodogster I had same problem. I solved it by changing localhost port. Add port number in function.yaml like port: (port number except 0).  i added 32001 from nuclio doc
 
 triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        port: 32001 <----- add this
        maxRequestBodySize: 33554432 # 32MB

**Comment by nmanovic** [comment] 2021-03-18 06:22
@davodogster , I cannot help to resolve local firewall problems. I will recommend to run commands from function.yaml without docker. If you can reproduce the issue without docker, ask your local administrator to setup your firewall properly.

**Comment by nmanovic** [comment] 2021-07-13 20:36
@davodogster , it looks like you have a similar issue to https://github.com/openvinotoolkit/cvat/issues/3059. Need to update nuclio till 1.6.4. I will close the issue.

**Closed by nmanovic** 2021-07-13 20:36 UTC
Labels: bug

**Comment by nmanovic** [comment] 2021-07-13 20:39
I hope the issue was resolved. Let's reopen it if we know how to reproduce. IOG works in my case without any problems. We are not able to help with local firewall configurations.
