### ISSUE TITLE
NO KITTI 1.0 Format in LOCALHOST:8080

### ISSUE THREAD

**Issue by hassan-mushtaq** [openvinotoolkit/cvat#4249] opened 2022-01-26 14:16 UTC
**cvat.org** has **KITTI 1.0** export format....

# while when using localhost 8080.... **_there is no KITTI format..._**

I am using **windows 10** 
Running through **docker steps**
#4234

**Comment by azhavoro** [comment] 2022-01-26 14:30
Duplicate of #4234, I've answered in the mentioned issue

**Closed by azhavoro** 2022-01-26 14:30 UTC
