### ISSUE TITLE
Email verification Problem

### ISSUE THREAD

**Issue by arcibiyo** [openvinotoolkit/cvat#3255] opened 2021-05-30 12:08 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/openvinotoolkit/cvat/blob/develop/site/content/en/docs/for-users/installation.md#email-verification)
- [ ] Searched [past issues](https://github.com/openvinotoolkit/cvat/issues/1283)

### Expected Behaviour
Fix could not login on the server error

### Current Behaviour
![image](https://user-images.githubusercontent.com/47760055/120103260-74c03080-c157-11eb-9d57-92deebc969f5.png)

### Possible Solution

- Edit **base.py** with 

```
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
```

- build cvat

```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
docker-compose up -d
```

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment] 2021-05-31 06:40
@arcibiyo
Please fill the issue template for the future task and provide cvat container logs

**Comment by bsekachev** [comment] 2021-07-26 08:54
I will close the issue, because there is not a response from your side. Please, do not hesitate to reopen it if you still have questions and ready to provide more details.

**Closed by bsekachev** 2021-07-26 08:54 UTC
Labels: need info

**Comment by giordifungula** [comment] 2021-11-30 18:22
has this been resolved? currently having a similar issue.

**Comment by nmanovic** [comment] 2021-11-30 18:46
@giordifungula , could you please provide more information about the issue? Need a clear way to reproduce the issue on the latest develop version of CVAT.

**Comment by giordifungula** [comment] 2021-11-30 19:18
@nmanovic should I create a new Issue or just comment directly from here?

**Comment by giordifungula** [comment] 2021-11-30 19:55
# What Im currently trying to do. 

## I am using this [link](https://github.com/openvinotoolkit/cvat/issues/1283#issuecomment-886943114) to try and fix the issue of disabling self sign up on the login page.

### What steps I have done
- cd into cvat/settings 
- cp base.py base.py.backup
- open base.py
- added ACCOUNT_AUTHENTICATION_METHOD = 'username' inside base.py
- added ACCOUNT_CONFIRM_EMAIL_ON_GET = True inside base.py
- added ACCOUNT_EMAIL_REQUIRED = True inside base.py
- added ACCOUNT_EMAIL_VERIFICATION = 'mandatory' inside base.py
- ran docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f  build
- ran docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f up -d

## How am I running CVAT:
- I have an ec2 instance running version cvat:master branch changes on top of a version that I had running that had the proxy with the nginx server configured in the docker file.
- When I run commands ``` sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml build and sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d ``` to build the docker images 
- I'm unable to login as any users after these configs were applied to the base.py file and I build the docker images too.
- I, however, noticed that there is now a toast saying "You are not verified", if you try and log in as a user that is not verified, but no one is able to login.
- See screenshots below on what the output is
![Screenshot 2021-11-30 at 19 56 21](https://user-images.githubusercontent.com/27930281/144117708-5d74d94c-a575-417b-9f86-b2cc5781770f.png)

Note:
- It looks like when I reset the default base.py settings and add back the old configs it works fine, however, the problem still persists about users being able to automatically login without being verified by the admin.
- However, I would like those configs
 added ACCOUNT_AUTHENTICATION_METHOD = 'username' inside base.py
- added ACCOUNT_CONFIRM_EMAIL_ON_GET = True inside base.py
- added ACCOUNT_EMAIL_REQUIRED = True inside base.py
- added ACCOUNT_EMAIL_VERIFICATION = 'mandatory' inside base.py
to be added to my base.py file but I would like to be able to login as any user and also only be able to login after admin verifies the user.
- Please let me know if you can replicate this issue or if you can advise on how to get this working whilst still being able to login as any user and keep the latest configs

**Comment by arcibiyo** [comment] 2022-05-13 07:27
@nmanovics
When ı adjust Email verification settings like in this link [https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#email-verification](url)

I used just this code script 

> ACCOUNT_AUTHENTICATION_METHOD = "username"
> ACCOUNT_CONFIRM_EMAIL_ON_GET = True
> ACCOUNT_EMAIL_REQUIRED = True
> ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Email backend settings for Django
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
`
Finally, ı got _Could not login on the server
Error: Request failed with
[log.txt](https://github.com/openvinotoolkit/cvat/files/8685014/log.txt)
 status code 502. "Bad Gateway"_  error 

My docker logs >
