### ISSUE TITLE
Issue loading serverless function , error: processor.yaml is a directory

### ISSUE THREAD

**Issue by thangvip4321** [openvinotoolkit/cvat#2024] opened 2020-08-12 15:36 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](#1977 )

### Expected Behaviour

nuctl deploy should deploy the function to CVAT.
### Current Behaviour

The error happens in the deploy process, not the build process. Here's the log (with --verbose tag):
[log_cvat.txt](https://github.com/opencv/cvat/files/5063734/log_cvat.txt)
It failed on Mask RCNN ,ADAS , and Deep Extreme Cut, as far as i have tried. Although i think the result will be identical to other functions.

### Possible Solution

https://github.com/nuclio/nuclio/issues/622 
it seems like in that issue /tmp: in nuclio and /tmp in docker does not point to the same thing in local machine. 

### Steps to Reproduce (for bugs)

1. docker-compose up -d
2. `nuctl deploy --project-name cvat --path /home/thang/cvat/serverless/openvino/omz/public/mask_rcnn_inception_resnet_v2_atrous_coco/nuclio --volume /home/thang/cvat/serverless/openvino/common:/opt/nuclio/common --platform local --verbose`
(Neither root nor non-root command works)

### Your Environment

- Git hash commit (`git log -1`): 2c661020b61b6c87efe086a8de6aeeb7052aa747
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.11
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04 ,

**Comment by nmanovic** [comment] 2020-09-01 07:10
@thangvip4321, can the problem be reproduced now?

**Comment by bsekachev** [comment] 2020-09-21 11:25
@thangvip4321 

I will close the issue since there aren't any response from you. 
Please, do not hesitate reopen if you are still experiencing it.

**Closed by bsekachev** 2020-09-21 11:25 UTC
Labels: question

**Comment by dberardo-com** [comment] 2022-01-22 13:48
i am having the same problem running nulcio on windows through docker compose, latest version
