### ISSUE TITLE
Autohide for popup should be changed

### ISSUE THREAD

**Issue by valeriyvan** [openvinotoolkit/cvat#2713] opened 2021-01-24 22:58 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Currently if label selected in dropdown is inside of bounds of popup, popup stays open allowing annotator to choose labelling method pressing [Shape] or [Track] buttons:

![1](https://user-images.githubusercontent.com/1630974/105646300-77f09a80-5e9f-11eb-9fec-0b2dcb432184.gif)

But if selected label is beyond bounds of popup, it hides. Annotator has to open popup once again to choose labelling method by pressing [Shape] or [Track] buttons.:

![2a](https://user-images.githubusercontent.com/1630974/105646611-0fa2b880-5ea1-11eb-95ea-45a9c214491e.gif)

### Expected Behaviour

In both cases popup should not hide allowing annotator press [Shape] or [Track] buttons.

### Current Behaviour

Popup hides unexpectedly. Annotator has to open popup again.
 
### Possible Solution

Possible solution: if selected labels is inside bounds of popup, behaviour stays the same - popup hides. If selected label is beyond bounds of popup, it stays open until user presses [Shape] or [Track] buttons or until user moves mouse so that mouse pointer goes beyond right edge of popup (mouse y coordinate become greater then popup's greatest y coordinate).

### Steps to Reproduce (for bugs)

Look gifs attached.

### Your Environment

- Git hash commit (`git log -1`): 226c2f2
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? n/a
- Operating System and version (e.g. Linux, Windows, MacOS): n/a
- Code example or link to GitHub repo or gist to reproduce problem: n/a
- Other diagnostic information / logs: n/a

### Next steps
n/a

**Comment by bsekachev** [comment] 2021-01-25 09:55
Duplicate of #2230

**Comment by valeriyvan** [comment] 2021-01-25 11:11
> Duplicate of #2230

Yes, but #2230 is about different popups.

**Comment by valeriyvan** [comment] 2021-01-25 11:11
Any plans to fix?

**Comment by bsekachev** [comment] 2021-01-26 08:17
Yes, we have plans to fix it.

**Comment by valeriyvan** [comment] 2021-01-26 08:33
> Yes, we have plans to fix it.

Create! Does it fit next release?

**Comment by bsekachev** [comment] 2021-01-26 09:02
We will try to implement it earlier than in next release. It will be available in develop branch

**Closed** 2021-02-20 09:27 UTC
Labels: bug
