### ISSUE TITLE
Data empty error on export with Yolo format

### ISSUE THREAD

**Issue by zeynepkoyun** [openvinotoolkit/cvat#3918] opened 2021-11-18 07:13 UTC
Hi @bsekachev @zhiltsov-max @nmanovic 

When I want to get the dataset of the task processed with cvat in yolo format, the file content is empty.

**Comment by zhiltsov-max** [comment] 2021-11-18 07:35
Hi, the format only works with bounding box annotations. Can it be the reason in you case?
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/format-yolo/

**Comment by zeynepkoyun** [comment] 2021-11-18 07:45
> Hi, the format only works with bounding box annotations. Can it be the reason in you case? https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/format-yolo/

Thank you for your answer.
I checked the structure, now I looked at the link you gave, but the .txt file contents seem empty.

Here are the screenshots of the build:
![cvatyolo](https://user-images.githubusercontent.com/53746550/142373274-8d531a90-cb56-4b7b-a854-7b9e0b085729.png)
![cvatbos](https://user-images.githubusercontent.com/53746550/142373315-1efa52e0-b415-4f07-ba1f-888afd0b24ee.png)

**Comment by zhiltsov-max** [comment] 2021-11-18 07:58
Which annotations you're trying to export?

**Comment by zeynepkoyun** [comment] 2021-11-18 08:01
> Which annotations you're trying to export?

I get this error when I want to import with "Yolo 1.1" format in export task function.

**Comment by zhiltsov-max** [comment] 2021-11-18 08:06
I understand, but the question is about the annotation types - boxes, polygons, lines etc. What are you trying to export?

**Comment by zeynepkoyun** [comment] 2021-11-18 08:24
> I understand, but the question is about the annotation types - boxes, polygons, lines etc. What are you trying to export?

Just like that, the values of the boxes are returned in pascalvoc format. I want to get the same values with the yolo format.

**Comment by zhiltsov-max** [comment] 2021-11-18 10:02
So, you're trying to:
1. Import PASCAL VOC annotations to a task
2. Modify annotations in CVAT (the UI displays annotations correctly)
3. Export in YOLO format

You're working with bounding boxes. 

Is it correct? If so, this scenario should be supported pretty well, so there may be a bug. Do any other formats produce non-empty outputs? "CVAT for images", for example, or just PASCAL VOC?

**Comment by zeynepkoyun** [comment] 2021-11-18 11:03
> So, you're trying to:
> 
> 1. Import PASCAL VOC annotations to a task
> 2. Modify annotations in CVAT (the UI displays annotations correctly)
> 3. Export in YOLO format
> 
> You're working with bounding boxes.
> 
> Is it correct? If so, this scenario should be supported pretty well, so there may be a bug. Do any other formats produce non-empty outputs? "CVAT for images", for example, or just PASCAL VOC?

pascal voc format is correct and also coco format is correct but yolo is empty

**Comment by zhiltsov-max** [comment] 2021-11-18 11:25
Ok, please give us some information to reproduce the error. CVAT version, logs, annotations - if possible etc, like the issue template advises.

**Comment by zeynepkoyun** [comment] 2021-11-18 11:31
> Ok, please give us some information to reproduce the error. CVAT version, logs, annotations - if possible etc, like the issue template advises.

When labeling our data, we choose the polygon shape. The version information and the part where the error is received are as follows.
![cvatVersion](https://user-images.githubusercontent.com/53746550/142407581-f9a7be2d-ea8f-47c3-aa83-3161fe834db5.png)

![cvatyolo1](https://user-images.githubusercontent.com/53746550/142407593-d59fa3ba-8415-46da-8c4a-2b48c4a11414.png)

**Comment by zhiltsov-max** [comment] 2021-11-18 12:56
> we choose the polygon shape

Probably, this is the problem, because

> the format only works with bounding box annotations.

**Comment by zeynepkoyun** [comment] 2021-11-18 12:58
> > we choose the polygon shape
> 
> Probably, this is the problem, because
> 
> > the format only works with bounding box annotations.


OK, I'm checking this.
What about the status of being added as a feature?

**Comment by zhiltsov-max** [comment] 2021-11-18 15:51
This format is not supposed to be used for polygons, so we don't have such plans yet. It has a specific use case, related to the popular [YOLO object detection framework](https://pjreddie.com/darknet/yolo/), which works with boxes. How do you want to use polygons in the resulting dataset?

**Comment by zeynepkoyun** [comment] 2021-11-19 05:43
> This format is not supposed to be used for polygons, so we don't have such plans yet. It has a specific use case, related to the popular [YOLO object detection framework](https://pjreddie.com/darknet/yolo/), which works with boxes. How do you want to use polygons in the resulting dataset?


Now we have a large dataset marked as polygon and we want to take it in the yolo format and use it with the yolo models as well.

I understand it like this, after the labels marked as polygon are converted to box form, but usage is allowed, right?

**Comment by zhiltsov-max** [comment] 2021-11-19 15:04
If you want to convert polygons to boxes, you can try to use [Datumaro](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/transform/):

1. Export the CVAT task in the Datumaro format, unzip

2. 
``` bash
pip install datumaro[default]
datum transform -t shapes_to_boxes -o boxes_dataset path/to/dataset:datumaro
datum convert -i boxes_dataset -if datumaro -f yolo -o yolo_boxes_dataset
```

**Comment by zeynepkoyun** [comment] 2021-11-19 15:40
> If you want to convert polygons to boxes, you can try to use [Datumaro](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/transform/):
> 
> 1. Export the CVAT task in the Datumaro format, unzip
> 
> ```shell
> pip install datumaro[default]
> datum transform -t shapes_to_boxes -o boxes_dataset path/to/dataset:datumaro
> datum convert -i boxes_dataset -if datumaro -f yolo -o yolo_boxes_dataset
> ```
thank you i will try and let you know

**Comment by nmanovic** [comment] 2021-11-19 18:41
@zeynepkoyun , it looks like Max answered your question. I will close the issue.

**Closed by nmanovic** 2021-11-19 18:41 UTC

**Comment by zeynepkoyun** [comment] 2021-11-22 05:54
Hi @zhiltsov-max 
After exporting the one you mentioned with "datumaro 1.0" format, I was able to convert it to yolo format. Thanks for your interest.
