### ISSUE TITLE
Helm Install results in a CVAT instance where I am unable to login

### ISSUE THREAD

**Issue by bhlarson** [openvinotoolkit/cvat#3725] opened 2021-09-24 23:07 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Following the [helm-chart install](https://github.com/openvinotoolkit/cvat/tree/develop/helm-chart) procedure produces a CVAT instance that is impossible to log in to:
![login failure screen shot](https://user-images.githubusercontent.com/6820994/134747669-276d57a2-56e9-49a2-8a74-168e2329a281.png)

### Expected Behaviour

I would expect the superuser login described in [How to crate a superuser](https://github.com/openvinotoolkit/cvat/tree/v1.6.0/helm-chart) or "Create an account" to successfully log into the CVAT annotation tool.  

### Current Behaviour

Instead, The "Could not check autorization on the sever" message was returned each time.  The error details on the browser console only returns "Not Allowed" which is not helpful in diagnosing the problem.

## Helm Install:
Helm Overrides:
```console
$ cat helm-chart/values.override.yaml
postgresql:
  secret:
    password: cvat_passwd
    postgres_password: cvat_passwd
    replication_password: cvat_passwd
```

Helm Install from clone of CVAT repository
```console
$ helm upgrade cvat --install ./helm-chart -f ./helm-chart/values.yaml -f ./helm-chart/values.override.yaml --namespace cv --create-namespace
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2488/credentials/client.config
Release "cvat" does not exist. Installing it now.
NAME: cvat
LAST DEPLOYED: Fri Sep 24 14:27:00 2021
NAMESPACE: cv
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

CVAT runtime following helm install:
```console
$ kubectl get all -n cv
NAME                                 READY   STATUS    RESTARTS   AGE
pod/cvat-frontend-54674747d6-n8ccf   1/1     Running   0          65s
pod/cvat-backend-6f7d85f558-4tqnk    1/1     Running   0          65s
pod/cvat-postgresql-0                1/1     Running   0          65s
pod/cvat-redis-master-0              1/1     Running   0          65s

NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/cvat-redis-headless        ClusterIP   None             <none>        6379/TCP   66s
service/cvat-postgresql-headless   ClusterIP   None             <none>        5432/TCP   66s
service/cvat-postgresql            ClusterIP   10.152.183.4     <none>        5432/TCP   65s
service/cvat-redis-master          ClusterIP   10.152.183.93    <none>        6379/TCP   65s
service/cvat-frontend-service      ClusterIP   10.152.183.232   <none>        80/TCP     65s
service/cvat-backend-service       ClusterIP   10.152.183.143   <none>        8080/TCP   65s

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cvat-frontend   1/1     1            1           65s
deployment.apps/cvat-backend    1/1     1            1           65s

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/cvat-frontend-54674747d6   1         1         1       65s
replicaset.apps/cvat-backend-6f7d85f558    1         1         1       65s

NAME                                 READY   AGE
statefulset.apps/cvat-postgresql     1/1     65s
statefulset.apps/cvat-redis-master   1/1     65s
```

Port forward backend:
```console
$ kubectl port-forward service/cvat-backend-service 8080:8080 -n cv
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
```
Port forward frontend:
```console
$ kubectl port-forward service/cvat-frontend-service 8880:80 -n cv
Forwarding from 127.0.0.1:8880 -> 80
```
Chrome version: Chrome/94.0.4606.61 Safari/537.36" "-"

### Context

Without the helm install, we cannot evaluate CVAT in our Kubernetes production environment.

### Your Environment

- Git hash commit (`git log -1`):
```console
$ git log -1
commit 8d03ed7959632d6f3ffd76020ad577fa409acfcd (HEAD, tag: v1.6.0, origin/master)
Merge: 56c9626a 476b2fcf
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Fri Sep 17 14:22:09 2021 +0300

    Merge branch 'release-1.6.0'
```
- Docker version `docker version` (e.g. Docker 17.0.05):
```console
$ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 nvidia:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Are you using Docker Swarm or Kubernetes?
Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS):
```console
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
Kubernetes and helm versions:
```console
$ snap list microk8s
Name      Version  Rev   Tracking     Publisher   Notes
microk8s  v1.22.2  2488  1.22/stable  canonical✓  classic
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.2-3+a4bd0397e1cb5e", GitCommit:"a4bd0397e1cb5e638a6a6464f759114ee2250ea1", GitTreeState:"clean", BuildDate:"2021-09-16T00:05:14Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.2-3+a4bd0397e1cb5e", GitCommit:"a4bd0397e1cb5e638a6a6464f759114ee2250ea1", GitTreeState:"clean", BuildDate:"2021-09-16T00:00:16Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Helm:
$ helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2488/credentials/client.config
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
Backend log:
```console
$ kubectl logs deployment.apps/cvat-backend -n cv --tail=20
debug1: process_message: socket 1 (fd=4) type 11

2021-09-24 21:36:09,072 DEBG 'rqworker_default_0' stderr output:
DEBUG - 2021-09-24 21:36:09,072 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-09-24 21:36:09,073 DEBG 'rqworker_default_1' stderr output:
DEBUG - 2021-09-24 21:36:09,072 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-09-24 21:36:09,474 DEBG 'rqworker_low' stderr output:
DEBUG - 2021-09-24 21:36:09,474 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-09-24 21:42:54,091 DEBG 'rqworker_default_1' stderr output:
DEBUG - 2021-09-24 21:42:54,091 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-09-24 21:42:54,092 DEBG 'rqworker_default_0' stderr output:
DEBUG - 2021-09-24 21:42:54,091 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-09-24 21:42:54,492 DEBG 'rqworker_low' stderr output:
DEBUG - 2021-09-24 21:42:54,491 - worker - Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
```
Frontend Log:
```console
$ kubectl logs deployment.apps/cvat-frontend -n cv --tail 25
127.0.0.1 - - [24/Sep/2021:21:31:34 +0000] "OPTIONS /api/v1/auth/password/change HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:31:34 +0000] "OPTIONS /api/v1/auth/password/reset HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:23 +0000] "GET /cvat-ui.f9340a4e583f3306fd17.min.js HTTP/1.1" 200 5955484 "http://localhost:8880/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:24 +0000] "OPTIONS /api/v1/auth/password/change HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:24 +0000] "OPTIONS /api/v1/auth/password/reset HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:31 +0000] "GET / HTTP/1.1" 200 1045 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:31 +0000] "GET /cvat-ui.f9340a4e583f3306fd17.min.js HTTP/1.1" 200 5955484 "http://localhost:8880/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:32 +0000] "GET /api/v1/users/self HTTP/1.1" 200 1045 "http://localhost:8880/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:32 +0000] "GET /download.worker.cb069004e9ace5f89e8e.js HTTP/1.1" 200 16721 "http://localhost:8880/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:32 +0000] "GET /favicon.ico HTTP/1.1" 200 102581 "http://localhost:8880/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:32 +0000] "GET /api/v1/restrictions/user-agreements HTTP/1.1" 200 1045 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:32 +0000] "OPTIONS /api/v1/auth/password/change HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:32 +0000] "OPTIONS /api/v1/auth/password/reset HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:42 +0000] "GET /cvat-ui.f9340a4e583f3306fd17.min.js.map HTTP/1.1" 200 19371636 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:34:42 +0000] "GET /download.worker.cb069004e9ace5f89e8e.js.map HTTP/1.1" 200 77935 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:46 +0000] "GET /auth/login HTTP/1.1" 200 1045 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:46 +0000] "GET /cvat-ui.f9340a4e583f3306fd17.min.js.map HTTP/1.1" 200 19371636 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:46 +0000] "GET /favicon.ico HTTP/1.1" 200 102581 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:46 +0000] "OPTIONS /api/v1/auth/password/reset HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:46 +0000] "OPTIONS /api/v1/auth/password/change HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:52 +0000] "GET /auth/login HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:52 +0000] "GET /cvat-ui.f9340a4e583f3306fd17.min.js.map HTTP/1.1" 200 19371636 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:52 +0000] "GET /favicon.ico HTTP/1.1" 200 102581 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:52 +0000] "OPTIONS /api/v1/auth/password/change HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
127.0.0.1 - - [24/Sep/2021:21:38:52 +0000] "OPTIONS /api/v1/auth/password/reset HTTP/1.1" 405 559 "http://localhost:8880/auth/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) 
```

### Next steps
- Added the above information to the https://gitter.im/opencv-cvat/public thread by Asal Jalilvand @AsalJalilvand Aug 25 14:29
- I believe there is failed communications between server pods because the same software version works well in Docker Compose.  
- Compare docker compose yaml and helm install to identify the missing communication

**Comment by shortcipher3** [comment] 2021-10-09 02:38
I've also been looking at this, but with an external postgres sql database.  I installed with an override file:

```
helm upgrade cvat --install . -f values.yaml -f values.override.yaml --namespace cvat-namespace
```

Containing `enabled: false`, `user: postgres`, `password: mypassword`, `host=my_ip`.

After install I can't login or create a super user using:
```
kubectl exec -it --namespace $HELM_RELEASE_NAMESPACE $BACKEND_POD_NAME -c cvat-backend-app-container -- python manage.py createsuperuser
```

I get errors around the database usage.

To understand I logged in and took a look around: 
```
$ kubectl exec -it --namespace $HELM_RELEASE_NAMESPACE $BACKEND_POD_NAME -c cvat-backend-app-container -- bash
$ env | grep -i postgres
CVAT_POSTGRES_DBNAME=cvat
CVAT_POSTGRESQL_SERVICE_HOST=10.3.241.133
CVAT_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
CVAT_POSTGRES_PASSWORD=cvat_postgresql
CVAT_POSTGRESQL_PORT_5432_TCP_PORT=5432
CVAT_POSTGRESQL_SERVICE_PORT=5432
CVAT_POSTGRES_USER=cvat
CVAT_POSTGRESQL_PORT=tcp://10.3.241.133:5432
CVAT_POSTGRES_HOST=cvat-postgresql
CVAT_POSTGRESQL_SERVICE_PORT_TCP_POSTGRESQL=5432
CVAT_POSTGRESQL_PORT_5432_TCP_ADDR=10.3.241.133
CVAT_POSTGRESQL_PORT_5432_TCP=tcp://10.3.241.133:5432
```

The password is not the one I set, ip address isn't the one I set, etc.  So I changed the environment variables from the terminal and was able to successfully create a user:
```
$ export CVAT_POSTGRES_USER=postgres
$ export CVAT_POSTGRES_HOST=my_ip
$ export CVAT_POSTGRESQL_SERVICE_HOST=my_ip
$ export CVAT_POSTGRESQL_PORT=tcp://my_ip5432
$ export CVAT_POSTGRESQL_PORT_5432_TCP_ADDR=my_ip
$ export CVAT_POSTGRESQL_PORT_5432_TCP=tcp://my_ip:5432
$ export CVAT_POSTGRES_PASSWORD=mypassword
$ python3 manage.py createsuperuser
```

I have been tinkering with the `values.yml` and `values.override.yml` files and haven't been able to see any change in my environment variables.

**Comment by shortcipher3** [comment] 2021-10-09 05:18
I found a bug related to using an external database and made a fix here: #3779

I am able to run `createsuperuser` successfully, however I'm still not able to log in with the account that I have created.

I checked the frontend app and noticed that it also has some environment variables related to the postgres database that are not using my settings in the `values.override.yaml`.  I suspect that is the cause of my login problem.

```
$ kubectl exec -it --namespace $HELM_RELEASE_NAMESPACE $FRONTEND_POD_NAME -c cvat-frontend-app-container -- sh
# env | grep -i postgres
```

**Comment by TianbaoLi** [comment] 2021-10-10 17:25
I was experiencing the same issue last week. Similarly, I deployed CVAT on Kubernetes cluster with my modified deployment files. The main reason of this issue is about request routing on k8s cluster. Ingress on k8s is more complicated than the original docker-compose network.
From your logs in deployment.apps/cvat-frontend, you can see that a lot of request are routed to frontend. However:
- only these should be routed to frontend pod: /cvat-ui.f9340a4e583f3306fd17.min.js, /favicon.ico
- these should be routed to backend pod: /api/v1/auth/*, /api/v1/users/*, /auth/login, ...

I used ingress to configure routing. I see ingress is mentioned in helm chart but routing rules are not configured correctly.
Hope these can help you debug. Deploying CVAT on k8s without official support is painful.

**Comment by TianbaoLi** [comment] 2021-10-12 20:48
FYI, I'm using CVAT 1.6.
Upstream CVAT version: 'release-1.6.0' 8d03ed7959632d6f3ffd76020ad577fa409acfcd

**Comment by nmanovic** [comment] 2021-11-20 11:53
@TianbaoLi , thanks for comments and your suggestions.

@bhlarson , we are going to support helm charts officially in the nearest future. For now I will close the issue.

**Closed by nmanovic** 2021-11-20 11:53 UTC
Labels: bug

**Comment by chao3150** [comment] 2021-12-16 02:42
> I was experiencing the same issue last week. Similarly, I deployed CVAT on Kubernetes cluster with my modified deployment files. The main reason of this issue is about request routing on k8s cluster. Ingress on k8s is more complicated than the original docker-compose network. From your logs in deployment.apps/cvat-frontend, you can see that a lot of request are routed to frontend. However:
> 
> * only these should be routed to frontend pod: /cvat-ui.f9340a4e583f3306fd17.min.js, /favicon.ico
> * these should be routed to backend pod: /api/v1/auth/_, /api/v1/users/_, /auth/login, ...
> 
> I used ingress to configure routing. I see ingress is mentioned in helm chart but routing rules are not configured correctly. Hope these can help you debug. Deploying CVAT on k8s without official support is painful.

Thanks very much. I use this configuration in k8s and work

```yaml
spec:
  rules:
    - host: myhost
      http:
        paths:
          - path: /
            backend:
              serviceName: cvat-ui
              servicePort: 80
          - path: /api
            backend:
              serviceName: cvat-server
              servicePort: 8080
```

**Comment by zerols** [comment] 2022-07-07 06:21
if don't user ingress, only nodeport how should change routed
