### ISSUE TITLE
it does not seem to work with firefox

### ISSUE THREAD

**Issue by antonkulaga** [openvinotoolkit/cvat#3050] opened 2021-04-01 04:52 UTC
Whenever I try to login with Firefox ( 87.0, Ubuntu Based Linux Mint) I get:
```
Could not login on the server
Error: Request failed with status code 400. {"non_field_errors":["Unable to log in with provided credentials."]}.
```

**Comment by bsekachev** [comment] 2021-04-01 11:23
Hi @antonkulaga 

``Error: Request failed with status code 400. {"non_field_errors":["Unable to log in with provided credentials."]}.`` 
Is a server response, browser should not play any role here. Please, be sure you use valid credentials to login.

**Comment by antonkulaga** [comment] 2021-04-01 12:18
Same login and password works on Chrome and doesn't on firefox, I tested

**Comment by bsekachev** [comment] 2021-04-02 08:09
Be sure you have correct data sent under "Network" tab -> "Request" tab of the browser (first open Firefox dev tools, second try to login).

![Screenshot from 2021-04-02 11-04-55](https://user-images.githubusercontent.com/40690378/113396098-95f8e080-93a3-11eb-96bf-f78742e3194e.png)

Did you use cvat.org? Are you able to login there from Firefox?

**Comment by azhavoro** [comment] 2021-04-12 07:34
@antonkulaga The issue is still actual?

**Comment by nmanovic** [comment] 2021-04-15 04:54
@antonkulaga , please reopen the issue if it is actual. I will close it for now.

**Closed by nmanovic** 2021-04-15 04:54 UTC
Labels: need info, question
