### ISSUE TITLE
Searching frames without annotation

### ISSUE THREAD

**Issue by aschernov** [openvinotoolkit/cvat#2214] opened 2020-09-23 12:05 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Please, develop a setting or a filter to quickly find frames without any annotated objects at all.

### Current Behaviour

There is no corresponding option to quickly find such frames

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

This option is necessary to improve validation processes and quickly find missed frames.
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment] 2020-09-23 13:28
Duplicate of #284

**Closed** 2020-09-28 09:38 UTC
Labels: duplicate, enhancement
