### ISSUE TITLE
toomanyrequests: You have reached your pull rate limit

### ISSUE THREAD

**Issue by MagicCodess** [openvinotoolkit/cvat#2542] opened 2020-12-09 04:13 UTC
ERROR: Service 'cvat' failed to build : toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by azhavoro** [comment] 2020-12-09 06:54
There are new Docker policies, unfortunately we cannot change them.

**Comment by azhavoro** [comment] 2020-12-14 07:54
Let's keep the question open, it might be better to look for another docker registry.

**Comment by nmanovic** [comment] 2021-01-08 08:21
@azhavoro , the problem is really critical even for us. Could you please propose a short-term and long-term solutions?

**Comment by nmanovic** [comment] 2021-07-29 19:41
@azhavoro , is it fixed with github actions?

**Comment by nmanovic** [comment] 2021-11-24 08:22
It looks like the issue was resolved. I will close the issue.

**Closed by nmanovic** 2021-11-24 08:22 UTC
Labels: bug, customer
