### ISSUE TITLE
After uploading images into a task, when I try and open the job I all of a sudden get this error, and now it occurs on all projects, "Disk image is malformed"

### ISSUE THREAD

**Issue by ADLADLADL** [openvinotoolkit/cvat#2932] opened 2021-03-10 03:50 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
I was expecting the task to open, but I got an error as listed below:
_**Could not fetch frame data from the server
Error: . "\"cannot get requested data type: chunk, number: 0, quality: compressed\\ndatabase disk image is malformed\"".**_

### Current Behaviour
_**Could not fetch frame data from the server
Error: . "\"cannot get requested data type: chunk, number: 0, quality: compressed\\ndatabase disk image is malformed\"".**_

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by Shoaib7786** [comment] 2021-04-21 10:28
i am getting Error: . "\"cannot get requested data type: chunk, number: 0, quality: Quality.COMPRESSED\\nA invalid index number: -1\\nMax: 1\"" while opening the files in CVAT Server Version: 1.3, Please suggest a solution for this issue !!!

**Comment by azhavoro** [comment] 2021-05-18 07:29
@Shoaib7786 Sorry for the late response, please attach logs from `cvat` container and steps to reproduce the issue. Thanks

**Comment by bsekachev** [comment] 2021-07-26 08:54
I will close the issue, because there is not a response from your side. Please, do not hesitate to reopen it if you still have questions and ready to provide more details.

**Closed by bsekachev** 2021-07-26 08:54 UTC
Labels: need info
