### ISSUE TITLE
Cannot delete label in project

### ISSUE THREAD

**Issue by LukeAI** [openvinotoolkit/cvat#2929] opened 2021-03-09 13:05 UTC
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I am trying to update the labels of a project in the GUI of CVAT 1.2
I have accidentally added "right_traffic_light" twice and wish to delete one entry:

```
[
    {
        "name": "Right_traffic_light",
        "color": "#050768",
        "attributes": []
    },
    {
        "name": "right_traffic_light",
        "color": "#050768",
        "attributes": []
    },
    {
        "name": "Traffic_light",
        "color": "#d0a000",
        "attributes": []
    },
    {
        "name": "Truck",
        "color": "#906080",
        "attributes": []
    },
    {
        "name": "Person",
        "color": "#c06060",
        "attributes": []
    },
    {
        "name": "Car",
        "color": "#2080c0",
        "attributes": []
    }
]
```

When I delete right_traffic_light in the raw edit GUI and click Done nothing happens that I can see. If I refresh or even log out and log in again I find that the deletion has not persisted. If I check logs I see:

```
2021-03-09 12:57:50,108 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.108381 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] [2021-03-09 12:57:50,108] INFO cvat.server.project_4: Right_traffic_light label was updated

2021-03-09 12:57:50,109 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.108548 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] INFO:cvat.server.project_4:Right_traffic_light label was updated

2021-03-09 12:57:50,426 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.426225 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] [2021-03-09 12:57:50,425] INFO cvat.server.project_4: Traffic_light label was updated

2021-03-09 12:57:50,426 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.426429 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] INFO:cvat.server.project_4:Traffic_light label was updated

2021-03-09 12:57:50,475 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.475211 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] [2021-03-09 12:57:50,475] INFO cvat.server.project_4: Truck label was updated

2021-03-09 12:57:50,475 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.475387 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] INFO:cvat.server.project_4:Truck label was updated

2021-03-09 12:57:50,513 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.512967 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] [2021-03-09 12:57:50,512] INFO cvat.server.project_4: Person label was updated

2021-03-09 12:57:50,513 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.513184 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] INFO:cvat.server.project_4:Person label was updated

2021-03-09 12:57:50,563 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.562911 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] [2021-03-09 12:57:50,562] INFO cvat.server.project_4: Car label was updated

2021-03-09 12:57:50,563 DEBG 'runserver' stderr output:
[Tue Mar 09 12:57:50.563081 2021] [wsgi:error] [pid 1088:tid 139797558925056] [remote 172.28.0.4:57834] INFO:cvat.server.project_4:Car label was updated

```

**Comment by ActiveChooN** [comment] 2021-05-07 10:46
@LukeAI, should be resolved via #2881, so i am closing the issue. Please, re-open it, if the problem is still reproducible.

**Closed by ActiveChooN** 2021-05-07 10:46 UTC
Labels: bug
