### ISSUE TITLE
404 not found while accessing the cvat with our domain

### ISSUE THREAD

**Issue by KALALRANJITHKUMAR** [openvinotoolkit/cvat#3533] opened 2021-08-10 06:44 UTC
<img width="390" alt="Capture" src="https://user-images.githubusercontent.com/16818767/128820575-6691954a-0971-4cc8-a5d3-4aa2589a6dee.PNG">

**Comment by azhavoro** [comment] 2021-08-10 06:58
https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-change-default-cvat-hostname-or-port

**Comment by azhavoro** [comment] 2021-08-10 06:59
Duplicate of https://github.com/openvinotoolkit/cvat/issues/3526
Please dont duplicate the issues.

**Closed by azhavoro** 2021-08-10 06:58 UTC
