### ISSUE TITLE
Could not create task: ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by plangenhuizen** [openvinotoolkit/cvat#2226] opened 2020-09-25 13:58 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have installed CVAT on an Azure VM, and the tool is accessible on port 8080 from outside. I can sign up new users, and access the admin panel. However, if I create a new task (no tasks are created yet) and I submit it, I get back an error that says that "Error, cannot create task". 

### Expected Behaviour
A task should be created with the attached video file

### Current Behaviour
At accessing the tool, crtl+F12 reveals 1 error: 
 - GET http://jads001vmcvat.westeurope.cloudapp.azure.com:8080/analytics/app/kibana 404 (Not Found)

And after I submit the task and the file (a 600+mb avi file) two new errors show up after approximately 30-60 seconds:
 - xhr.js:160 POST http://jads001vmcvat.westeurope.cloudapp.azure.com:8080/api/v1/tasks/22/data net::ERR_CONNECTION_RESET
 - Error: Network Error.

Furthermore, during the 30-60 seconds, my whole internet connection goes down (for my whole house).

The output of the command `docker ps -a`:
```
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                            NAMES
5239867b8038        nginx:stable-alpine                    "/docker-entrypoint.…"   11 minutes ago      Up 11 minutes       0.0.0.0:8080->80/tcp             cvat_proxy
f19bd2901e44        cvat/ui                                "/docker-entrypoint.…"   11 minutes ago      Up 11 minutes       80/tcp                           cvat_ui
ff46fb50314a        cvat/server                            "/usr/bin/supervisord"   11 minutes ago      Up 11 minutes       8080/tcp, 8443/tcp               cvat
1c9168fa8721        redis:4.0-alpine                       "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes       6379/tcp                         cvat_redis
010dcc9a3a9c        postgres:10-alpine                     "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes       5432/tcp                         cvat_db
d4c1c8e469e0        quay.io/nuclio/dashboard:1.4.8-amd64   "sh -c ./runner.sh"      11 minutes ago      Up 11 minutes       80/tcp, 0.0.0.0:8070->8070/tcp   nuclio
8a3ba79658ae        alpine:3.11                            "/bin/sh -c '/bin/sl…"   2 hours ago         Up 2 hours                                           nuclio-local-storage-reader
```

The output of `docker logs cvat`:
```
2020-09-25 13:43:26,840 DEBG 'runserver' stdout output:
Successfully ran command.

2020-09-25 13:43:26,840 DEBG 'runserver' stderr output:
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace

2020-09-25 13:43:26,844 DEBG 'runserver' stdout output:
Server URL         : http://localhost:8080/
Server Root        : /tmp/cvat-server
Server Conf        : /tmp/cvat-server/httpd.conf
Error Log File     : /dev/stderr (INFO)
Request Capacity   : 5 (1 process * 5 threads)
Request Timeout    : 60 (seconds)
Startup Timeout    : 15 (seconds)
Queue Backlog      : 100 (connections)
Queue Timeout      : 45 (seconds)
Server Capacity    : 20 (event/worker), 20 (prefork)
Server Backlog     : 500 (connections)
Locale Setting     : C.UTF-8

2020-09-25 13:43:26,892 DEBG 'runserver' stderr output:
[Fri Sep 25 13:43:26.892276 2020] [wsgi:info] [pid 193:tid 139844220210240] mod_wsgi (pid=193): Starting process 'localhost:8080' with threads=5.
[Fri Sep 25 13:43:26.892419 2020] [mpm_event:notice] [pid 20:tid 139844220210240] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.7.1 Python/3.8 configured -- resuming normal operations
[Fri Sep 25 13:43:26.892503 2020] [mpm_event:info] [pid 20:tid 139844220210240] AH00490: Server built: 2020-08-12T19:46:17
[Fri Sep 25 13:43:26.892511 2020] [core:notice] [pid 20:tid 139844220210240] AH00094: Command line: 'apache2 (mod_wsgi-express) -f /tmp/cvat-server/httpd.conf -D MOD_WSGI_MPM_ENABLE_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_EVENT_MODULE -D MOD_WSGI_MPM_EXISTS_WORKER_MODULE -D MOD_WSGI_MPM_EXISTS_PREFORK_MODULE -D FOREGROUND'

2020-09-25 13:43:26,892 DEBG 'runserver' stderr output:
[Fri Sep 25 13:43:26.892744 2020] [wsgi:info] [pid 193:tid 139844220210240] mod_wsgi (pid=193): Python home /usr.
[Fri Sep 25 13:43:26.892791 2020] [wsgi:info] [pid 193:tid 139844220210240] mod_wsgi (pid=193): Initializing Python.

2020-09-25 13:43:26,915 DEBG 'runserver' stderr output:
[Fri Sep 25 13:43:26.915405 2020] [wsgi:info] [pid 193:tid 139844220210240] mod_wsgi (pid=193): Attach interpreter ''.

2020-09-25 13:43:26,920 DEBG 'runserver' stderr output:
[Fri Sep 25 13:43:26.920175 2020] [wsgi:info] [pid 193:tid 139844220210240] mod_wsgi (pid=193): Imported 'mod_wsgi'.

2020-09-25 13:43:26,920 DEBG 'runserver' stderr output:
[Fri Sep 25 13:43:26.920242 2020] [wsgi:info] [pid 193:tid 139844220210240] mod_wsgi (pid=193, process='localhost:8080', application=''): Loading Python script file '/tmp/cvat-server/handler.wsgi'.

2020-09-25 13:43:27,174 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK

2020-09-25 13:43:27,176 DEBG 'ssh-agent' stderr output:
debug1: process_message: socket 1 (fd=4) type 17

2020-09-25 13:43:27,178 DEBG 'ssh-agent' stderr output:
debug1: process_add_identity: add ssh-rsa SHA256:IkRmofpmo+Sv+honLmA5VCcGHePbz+9VbzZqJ6b2j3E "django@5da1c21f82ff" (life: 0) (confirm: 0) (provider: none)

2020-09-25 13:43:27,183 DEBG 'ssh-agent' stderr output:
debug2: fd 4 setting O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 11
```
The output of `docker logs cvat_db`:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-09-25 13:43:11.263 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-09-25 13:43:11.263 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-09-25 13:43:11.294 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-09-25 13:43:11.350 UTC [20] LOG:  database system was shut down at 2020-09-25 13:42:51 UTC
2020-09-25 13:43:11.370 UTC [1] LOG:  database system is ready to accept connections
2020-09-25 13:43:13.587 UTC [27] LOG:  incomplete startup packet
```

### Possible Solution
No idea. I have tried to rebuild the tool several times, but no difference in output

### Context
I am trying to create tasks for video annotation. These annotations should be quite basic, bounding boxes that are tracked through the video.

### Your Environment

- Docker version: 19.03.12
- Operating System and version (e.g. Linux, Windows, MacOS): Linux (ubuntu 18.04)
- Azure VM System: vCPUs 4 ; RAM 16 GiB

**Comment by azhavoro** [comment] 2020-09-28 07:12
@plangenhuizen Hi,
The size of uploaded file is limited to 500 MB by default: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/settings/base.py#L410,
Could you please try to create a task with a small video file or increase this limit?

**Comment by plangenhuizen** [comment] 2020-09-28 10:01
@azhavoro Thank you for your suggesting. Unfortunately, I receive the same error when I try to upload a file of 376 MB.

**Comment by azhavoro** [comment] 2020-09-29 13:25
@plangenhuizen I don't see any logs showing that the backend server received data and started the process of creating a task(like this: `INFO:rq.worker:default: cvat.apps.engine.task._create_thread(1, {'chunk_size': None, 'size': 0, 'image_quality': 70, 'start_frame': 0, 'sto...) (/api/v1/tasks/1`)
) 
Could you please try to create a task from several images or a really small video file?

**Comment by plangenhuizen** [comment] 2020-09-30 07:16
@azhavoro Indeed, that is not in the logs. If I create a task with two images, everything works. A task is created, and the line you mentioned appears in the log. However, if I try to create a task with a video file of size 65 MB, it fails with the above-described error. In the task creation page, I get the following messages:
`The task is being created on the server...`, 
followed by:
`The data is being uploaded to the server...`.
This message is there for a couple of minutes, after which the error `Could not create task - Error: Network Error.` appears on the top right of the window. Furthermore, nothing appears in the cvat log.

**Comment by azhavoro** [comment] 2020-09-30 07:46
Looks like a kind of network issue, could you open the browser dev tools (F12) and try to create a new task. Please attach a screenshot of the failed request to the server, I think it should be the request to the task data endpoint `/api/v1/tasks/<TASK_ID>/data`.

**Comment by plangenhuizen** [comment] 2020-09-30 08:06
Sure, here it is

![image](https://user-images.githubusercontent.com/53085102/94659396-81f4f900-0304-11eb-8801-8451927b79c4.png)

**Comment by azhavoro** [comment] 2020-10-05 08:29
I think there is some network issue as I said early, the POST request that uploads data to the server failed for some reason, so the task cannot be created. Could you please try to create a new task from another computer?
Can you reproduce this issue on cvat.org?

**Comment by azhavoro** [comment] 2021-02-18 09:52
@plangenhuizen  I'll close the issue. Don't hesitate to reopen if the issue is still actual for you.

**Closed by azhavoro** 2021-02-18 09:52 UTC
