### ISSUE TITLE
fBRS is failing both in cvat.org and self-hosting

### ISSUE THREAD

**Issue by arasharchor** [openvinotoolkit/cvat#2326] opened 2020-10-16 00:47 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

fBRS is raising an issue both in a local server and cvat.org

### Expected Behaviour
Being able to use fBRS properly.

### Current Behaviour
Interaction error occurred
Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations".

### Steps to Reproduce (for bugs)
registering in cvat.org

1.choosing fBRS tool as an interactive tool.
2. clicking on an object

### Your Environment
cvat.org

**Comment by davodogster** [comment] 2020-10-16 02:53
@nmanovic Exact same problem for me (finally setup ubuntu WSL 2 Docker Daemon on windows working well) Nuclio working, but None of the Cvat serverless functions work on my localhost.
Errors when I try to use F-BRS

![image](https://user-images.githubusercontent.com/46079516/96207401-a4a33500-0fc7-11eb-82cf-180ec4fe518a.png)
![image](https://user-images.githubusercontent.com/46079516/96207425-b553ab00-0fc7-11eb-9fa4-14cc4768450c.png)


Regards,
Sam

**Comment by davodogster** [comment] 2020-10-18 21:55
@nmanovic When using the curl command for dextr and f-brs I had to add the -v param in the yaml file otherwise it fails. (Might be a permission/api access restriction at my end)

**Comment by smajida** [comment] 2020-10-21 15:22
@davodogster @nmanovic 

I can confirm what @davodogster has experienced. For me also Maskrcnn with Tensorflow as well as fBRS do not function properly. However, the Maskrcnn without tensorflow works for me.

**Comment by smajida** [comment] 2020-10-22 00:32
@davodogster @nmanovic 

Today I pulled the repository and rebuilt it. It seems fBRS is working for the "left click" part which is selecting the area, but the "right click" excluding the area is not working. 

The current behavior is: by right click, it seems it does some processing as I have to wait for a few seconds, but no changes are applied to exclude the selected area.

The Tensorflow implementation of MaskRCNN is still failing.

**Comment by nmanovic** [comment] 2020-10-22 05:54
@smajida ,

> Today I pulled the repository and rebuilt it. It seems fBRS is working for the "left click" part which is selecting the area, but the "right click" excluding the area is not working.

Negative points are not used at the moment. It is true. We will fix all found problems by our community. Just need some time. Thanks for your patience and reporting all these problems.

**Comment by smajida** [comment] 2020-10-22 23:19
@nmanovic Thanks Nikita

Please let me know you would like this issue to be closes at this status or we can keep it open until the negative points are  implemented.

**Comment by nmanovic** [comment] 2020-10-25 19:53
@smajida , negative points will be fixed in my next PR: https://github.com/openvinotoolkit/cvat/pull/2347.

**Comment by nmanovic** [comment] 2021-02-10 12:55
fBRS is working on cvat.org and locally. I will close the bug request. Don't hesitate to reopen if it is still an issue.

**Closed by nmanovic** 2021-02-10 12:55 UTC
Labels: bug
