### ISSUE TITLE
Filters and sorting for jobs and tasks

### ISSUE THREAD

**Issue by nstolyarov** [openvinotoolkit/cvat#2959] opened 2021-03-16 11:23 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

We are running a large project in CVAT with a lot of Tasks and Jobs. It is very difficult to navigate over them. If the Jobs/Tasks list could be filtered and sorted (by assignee, reviewer, status, etc.), grouped by same parameters, it would be very convenient.

### Expected Behaviour
Get the ability to filter and sort Jobs/Tasks by assignee, reviewer, status, etc.

### Current Behaviour
No any filtering, sorting mechanism in CVAT.
### Possible Solution
Add filters and sorting to CVAT Jobs/Tasks list.

### Context

It is difficult to navigate if there are many Jobs /Tasks in the list. This feature can help.
### Your Environment
- Git hash commit (`git log -1`): commit 7a2dcfff61626dbfdaa694127fc1cff8ee10e000 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Anastasia Yasakova <anastasia.yasakova@intel.com>
Date:   Tue Mar 9 10:41:33 2021 +0300
- Docker version `docker version` (e.g. Docker 17.0.05):  20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): GNU/Linux Ubuntu
4.15.0-136-generic
x86_64

**Comment by bsekachev** [comment] 2021-03-16 16:06
@nstolyarov 

CVAT has such options. Please, refer to user guide.

```
There are several options how to use the search.

Search within all fields (owner, assignee, task name, task status, task mode).
To execute enter a search string in search field.

Search for specific fields. How to perform:
owner: admin - all tasks created by the user who has the substring "admin" in his name
assignee: employee - all tasks which are assigned to a user who has the substring "employee" in his name
name: mighty - all tasks with the substring "mighty" in their names
mode: annotation or mode: interpolation - all tasks with images or videos.
status: annotation or status: validation or status: completed - search by status
id: 5 - task with id = 5.

Multiple filters. Filters can be combined (except for the identifier) ​​using the keyword AND:
mode: interpolation AND owner: admin
mode: annotation and status: annotation
```

**Comment by bsekachev** [comment] 2021-03-16 16:19
Partial duplicate of #899

**Comment by nstolyarov** [comment] 2021-03-17 07:48
@bsekachev  thank you for your answer!

If I understand right there are no filter and sort options for jobs. So I can not enable displaying only those jobs that are on validation e.g.

**Comment by bsekachev** [comment] 2021-03-17 08:02
@nstolyarov 

Yes, there aren't any ways to filter jobs.

**Closed** 2021-03-31 06:05 UTC
Labels: critical, duplicate, enhancement

**Comment by keshva23** [comment] 2021-12-06 12:58
I had a same requirement of displaying assigned jobs to users.  How that can be implemented?

**Comment by bsekachev** [comment] 2021-12-06 13:04
Hi @keshva23 
The issue was implemented. Please, refer to attached pull request.

**Comment by keshva23** [comment] 2021-12-06 13:09
> Hi @keshva23 The issue was implemented. Please, refer to attached pull request.

@bsekachev Can you please attached the new pull request.?
